# Generated by Django 4.1.4 on 2022-12-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('publish_year', models.IntegerField(max_length=250)),
                ('pages', models.IntegerField(max_length=250)),
                ('age', models.IntegerField(max_length=250)),
                ('created_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
